### PR TITLE
FIX: gas metering failing if global imported when comes from another module

### PR DESCRIPTION
**Pull request by Jacarte**
This fix solves https://github.com/filecoin-project/Fuzzing-FVM/issues/5

### CODE REVIEW

**Comment by Stebalien** [comment]
I believe this was _partially_ intentional (although the old code was incorrect any which way):

 https://github.com/filecoin-project/fvm-wasm-instrument/blob/831ea787f36369bd5dabb3a4d13c0de7928b328c/src/gas_metering/mod.rs#L143

But your new code is more correct. We should be enforcing any "no global import" rules elsewhere.

Could you update that line in the docs to reflect the new behavior.

**Comment by Jacarte** [comment]
> We should be enforcing any "no global import" rules elsewhere. 

Then this can be a previous check, before injecting the new gas global https://github.com/filecoin-project/fvm-wasm-instrument/blob/831ea787f36369bd5dabb3a4d13c0de7928b328c/src/gas_metering/mod.rs#L152 . WDYT?

**Comment by Jacarte** [comment]
Done

**Comment by Jacarte** [comment]
BTW, is not better to have a separated validation step (apart from the one made with wasmtime)? 
A previous validation stage could leverage in fast detection, preventing the time of a full instrumentation.
WDYT?

**Comment by Stebalien** [comment]
> BTW, is not better to have a separated validation step (apart from the one made with wasmtime)?

Absolutely.

**Pull request merged**
