### PR TITLE
Allow charging gas for charging gas

### PR DESCRIPTION
**Pull request by magik6k**
On top of https://github.com/filecoin-project/fvm-wasm-instrument/pull/11

This PR makes it possible to set rules for:
* Cost of gas charge
* Cost of calculating linear gas cost at runtime

### CODE REVIEW

**Comment by vyzo** [comment]
charging gas for charging gas... thats so meta... why?

**Comment by Stebalien** [comment]
> charging gas for charging gas... thats so meta... why?

Otherwise, an attacker could write pathological code that requires charging gas in many places. That pathological code would be more expensive than code that has _fewer_ gas charging points.

Basically, charging gas takes time, so we need to charge for that.

**Comment by vyzo** [comment]
you might as well make gas more expensive or charge more gas, that feels like the wrong way to address the attack vector.
Charging gas is not a user operation.

**Comment by Stebalien** [comment]
>  Charging gas is not a user operation.

In this case, it kind of is. We're encouraging code that has fewer branches, fewer dynamic operations, etc. Basically, the more branches you write, the more charge points you'll have, and the more gas you'll pay.

**Comment by Stebalien** [comment]
E.g., unroll your loops and pay less gas.

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
